#!/bin/bash

export IMAGE=image
export IMG_NAME=bullseye

if [ ! -f ".port" ]; then
    echo "Please start vm first"
fi;
port_num=$(cat .port);

# 编译 poc 并传送到内核
echo "compiling poc..."
bash trigger.sh
./scripts/scptovm poc

# 在登陆后执行 poc
ssh -i ${IMAGE}/${IMG_NAME}.id_rsa -p $port_num -o "StrictHostKeyChecking no" root@localhost "echo executing poc...; ./poc; bash -l"